
   
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing frontend dependencies...
      - cd application-code/web-tier
      - npm install
      - cd ../../application-code/backend-tier
      - echo Installing backend dependencies...
      - npm install

  build:
    commands:
      - echo Building frontend...
      - cd ../../application-code/web-tier
      - npm run build
      - echo Copying nginx.conf into build directory...
      - cp nginx.conf build/nginx.conf
      - echo Build complete.

artifacts:
  files:
    - appspec.yml
    - scripts/*
    - application-code/web-tier/build/**/*       
    - application-code/backend-tier/**/*         
    - application-code/web-tier/build/nginx.conf 
